baseURL = 'https://kaonmir.github.io/'
languageCode = "ko-kr"
title = 'Kaonmir Blog'
# theme = "github-style"
googleAnalytics = "G-4ZZF9KC2DG"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = 'Sunghun Son'
  description = "I'm living, loving, and learning my excellent life as an Engineer!"
  github = 'kaonmir'                              # github.com/YOUR_GITHUB_ID
  # facebook = "MeiK2333"
  # twitter = "MeiK2333"
  linkedin = "kaonmir"
  instagram = "sonrozana"
  # tumblr = "MeiK2333"
  email = "sonjeff@naver.com"
  url = "https://kaonmir.github.io"
  keywords = "blog, computer science, devops"
  rss = true
  lastmod = true
  userStatusEmoji = "🥰"
  favicon = "/images/favicon.png"
  location = "Republic of Korea"
  enableGitalk = true

  [params.gitalk]
    clientID = "8cbc72e597b160c18ec3" 
    clientSecret = "89f1e9690e6e8ca52f377e8cbf2328b9154ff502" 
    repo = "kaonmir.github.io"
    owner = "kaonmir"
    admin = "kaonmir"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  # [[params.links]]
  #   title = "Blog"
  #   # href = "https://meik2333.com"
  #   # icon = "https://meik2333.com/images/avatar.png"
  
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
